#!/usr/bin/env bash
# tmux-zoxide-opener: fuzzy pick a zoxide directory and open as tmux session
dir=$(zoxide query -l | fzf --reverse --header="Open project")
[ -z "$dir" ] && exit 0
name=$(basename "$dir" | tr '.' '-')
if tmux has-session -t "$name" 2>/dev/null; then
  tmux switch-client -t "$name"
else
  tmux new-session -d -s "$name" -c "$dir"
  tmux switch-client -t "$name"
fi
